services:
  fastapi:
    build: .
    container_name: fastapi-container
    ports:
      - "8500:8500"
    environment:
      - MONGOURL=mongodb://mongo:27017
    depends_on:
      - mongo
    entrypoint: ["sh", "-c", "python /app/initDatabase.py && uvicorn main:app --host 0.0.0.0 --port 8500"]

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local